spring.data.mongodb.uri=mongodb://root:Corgi2022@dds-uf64bb1a22a557d4118470.mongodb.rds.aliyuncs.com:3717/admin
spring.data.mongodb.database=corgi
spring.data.mongodb.auto-index-creation= true
server.port = 8885
server.tomcat.max-threads = 1000
logging.config = classpath:log4j2-spring.xml
logging.level.org.springframework.data.mongodb.core = DEBUG
spring.application.name=corgiActivity
spring.dubbo.server=true
spring.dubbo.registry=zookeeper://172.19.22.140:2181
spring.dubbo.protocol.port=20881
spring.dubbo.provider.threads=2000
spring.dubbo.provider.timeout=30000

spring.redis.host=r-uf6607cugmtd0glbje.redis.rds.aliyuncs.com
spring.redis.port=6379
spring.redis.password=Corgi2020

