spring.data.mongodb.uri=mongodb://localhost:27017/corgi

server.port = 8885
server.tomcat.max-threads = 1000
logging.config = classpath:log4j2-spring.xml
logging.level.org.springframework.data.mongodb.core = DEBUG
spring.application.name=corgiActivity
spring.dubbo.server=true
spring.dubbo.registry=zookeeper://127.0.0.1:2181
spring.dubbo.protocol.port=20881
spring.redis.host=localhost
spring.redis.port=6379

