spring.data.mongodb.uri=mongodb://root:Corgi2020@dds-2ze0fd7a5739a534-pub.mongodb.rds.aliyuncs.com:3717/admin
spring.data.mongodb.database=corgi
server.port = 8885
server.tomcat.max-threads = 1000
logging.config = classpath:log4j2-spring.xml
logging.level.org.springframework.data.mongodb.core = DEBUG
spring.application.name=corgiActivity
spring.dubbo.server=true
spring.dubbo.registry=zookeeper://172.19.22.140:2181
spring.dubbo.protocol.port=20881
spring.dubbo.threads=2000
spring.dubbo.provider.timeout=30000
spring.redis.host=localhost
spring.redis.port=6379

